spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 666666


server:
  port: 8088
  servlet:
    context-path: /zeng

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.webblog.entity
  config-location: classpath:BlogMapping.xml